version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys
      - run:
          command: echo '95.216.16.250 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKe3sl5pc/ljvfemlG2A/HYAZEWXU/xTPHE2S6PFIhVIk29oVAtjbpZm/OWT0U68Nc7Kgb5tdZpPvpL8TvUTkIU=' >> ~/.ssh/known_hosts
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - run:
          name: npm update
          command: npm update
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: CI="false" npm run build
      - run:
          name: deploy via scp
          command: |
            scp -r ~/repo/build/* admin@95.216.16.250:~/web/laformulefrancaisepro.com/public_html
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
